### ISSUE TITLE
Cannot install plugin from zip

### ISSUE THREAD

**Issue by pe5** [finnishtransportagency/QGIS-tieosoitetyokalu#16]
Several people from our project have had issues installing the plugin from zip as QGIS does not find it after install.

Lisäosaa 'QGIS-tieosoitetyokalu-1.0.1' ei voitu ladata 

ModuleNotFoundError: No module named 'QGIS-tieosoitetyokalu-1' 
Traceback (most recent call last):
  File "C:\PROGRA~1/QGIS32~1.10/apps/qgis-ltr/./python\qgis\utils.py", line 401, in loadPlugin
    __import__(packageName)
  File "C:\PROGRA~1/QGIS32~1.10/apps/qgis-ltr/./python\qgis\utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
ModuleNotFoundError: No module named 'QGIS-tieosoitetyokalu-1'

Python-versio: 3.9.5 (tags/v3.9.5:0a7dcbd, May  3 2021, 17:27:52) [MSC v.1928 64 bit (AMD64)] 
QGISin versio: 3.22.10-Białowieża Białowieża, 6a63fd37

**Comment by valttlapp** [comment]
@pe5 Make sure that when you download the plugin you choose the Osoitetyokalu.zip, not the Source code zip.
![image](https://user-images.githubusercontent.com/106655208/195783354-9f4abef5-0709-4a6e-b63e-3a1c622d7402.png)
Could you confirm if that fixes the issue.

**Comment by pe5** [comment]
Thank you, this was the problem, it works fine now!
________________________________
